#!/bin/sh

DIR=$(echo $1 | cut -d\. -f1 | sed "s/ /_/g")
echo "$DIR"

rm -r $DIR 2> /dev/null
mkdir $DIR
ffmpeg -i "$1" -an -vf crop=222:22:222:307 $DIR/line.mp4 -loglevel quiet
cd $DIR

#P1
function firstplayer() {
  mkdir "p1"
  ffmpeg -i line.mp4 -an -vf crop=60:22:0:0 p1/%05d.tiff -loglevel quiet
  cd "p1"
  ls | "$SSBB_SCRIPT_DIR/./num_ocr" > ../p1.txt
  cd ..
}

firstplayer &

#P2
mkdir "p2"
ffmpeg -i line.mp4 -an -vf crop=60:22:165:0 p2/%05d.tiff -loglevel quiet
cd "p2"
ls | "$SSBB_SCRIPT_DIR/./num_ocr" > ../p2.txt
cd ..
