#!/bin/bash

curl -s "$1" | \
  grep "watch?" | \
  sed 's/ /\n/g' | \
  grep "href" | \
  sed 's/href="//g' | \
  cut -d\& -f1 | \
  sort | \
  uniq | \
  sed "s|^|http://youtube.com|" > videos.txt

youtube-dl -f 18 -a videos.txt
